spring:
  datasource:
    url: jdbc:mysql://120.78.127.144/boss?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Hoyar@2022
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    druid:
      # 初始化大小(启动时创建多少个连接对象)
      initial-size:  5
      min-idle: 3
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 from DUAL
      test-on-return: false
      test-on-borrow: false
      test-while-idle: true
      pool-prepared-statements: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙   filters: stat,wall,log4j
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=50
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true

server:
  port: 8080
  tomcat:
    max-http-post-size: -1
mybatis-plus:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.wsy.dcxt.pojo
  global-config:
    id-type: 0
    field-strategy: 2
    capital-mode: true
    refresh-mapper: true


